let shopItemsData = [
  {
    id: 1,
    name: `JET BLACK T-SHIRT`,
    price: 3500,
    img: "./assets/products/p1.png",
    hoverImg: "./assets/products/p1hover.png",
    cat: "T-Shirt",
  },
  {
    id: 2,
    name: `"LOST IN THOUGHTS" APPLE GREEN T-SHIRT`,
    price: 3000,
    img: "./assets/products/p2.png",
    hoverImg: "./assets/products/p2hover.png",
    cat: "T-Shirt",
  },
  {
    id: 3,
    name: `"NAH JAWAB DE NAH SAWAL KAR" BEIGE T-SHIRT`,
    price: 3000,
    img: "./assets/products/p3.png",
    hoverImg: "./assets/products/p3hover.png",
    cat: "T-Shirt",
  },
  {
    id: 4,
    name: `"THE MINIMALS" RED T-SHIRT`,
    price: 3500,
    img: "./assets/products/p4.png",
    hoverImg: "./assets/products/p4hover.png",
    cat: "T-Shirt",
  },
  {
    id: 5,
    name: "CHARCOAL Basic Shorts with Stripes",
    price: 1050,
    img: "./assets/products/p5.png",
    hoverImg: "./assets/products/p5hover.png",
    cat: "Shorts",
  },
  {
    id: 6,
    name: "CHILL BLUE Basic Shorts with Stripes",
    price: 1050,
    img: "./assets/products/p6.png",
    hoverImg: "./assets/products/p6hover.png",
    cat: "Shorts",
  },
  {
    id: 7,
    name: "LAVENDER Basic Shorts with Stripes",
    price: 1050,
    img: "./assets/products/p7.png",
    hoverImg: "./assets/products/p7hover.png",
    cat: "Shorts",
  },
  {
    id: 8,
    name: "ROYAL GREEN Basic Shorts with Stripes",
    price: 1050,
    img: "./assets/products/p8.png",
    hoverImg: "./assets/products/p8hover.png",
    cat: "Shorts",
  },
  {
    id: 9,
    name: "Vans X Disney Belle",
    price: 6000,
    img: "./assets/products/vans1hover.png",
    hoverImg: "./assets/products/vans1.png",
    cat: "Shoes",
  },
  {
    id: 10,
    name: "VANS Old Skool X The North Face Yellow",
    price: 6500,
    img: "./assets/products/vans2.png",
    hoverImg: "./assets/products/vans2hover.png",
    cat: "Shoes",
  },
  {
    id: 11,
    name: "VANS Old Skool Pro Black",
    price: 6000,
    img: "./assets/products/vans3hover.png",
    hoverImg: "./assets/products/vans3.png",
    cat: "Shoes",
  },
  {
    id: 12,
    name: "Vans X Wandy Golf",
    price: 5000,
    img: "./assets/products/vans4.png",
    hoverImg: "./assets/products/vans4hover.png",
    cat: "Shoes",
  },
];
